//*-------------------------------------------------------------------*
//* STEP 2: RUN MATRIX CALCULATION WITH LE PERFORMANCE PROFILING
//*-------------------------------------------------------------------*
//RUNSIM   EXEC PGM=MATSIM,COND=(4,LT),
//         PARM='RPTSTG(ON),RPTOPTS(ON),HEAP(4K,4K,ANYWHERE,KEEP)/'
//STEPLIB  DD DISP=SHR,DSN=USER.LOAD.LIB
//* CEEDUMP captures diagnostic errors if the memory pool fails
//CEEDUMP  DD SYSOUT=*
//* CEOUT/SYSOUT captures the LE Storage Reports generated by RPTSTG
//CEEOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//SYSOUT   DD SYSOUT=*
