CREATE TABLE USER_MATRIX_PERF (
    RUN_TIMESTAMP  TIMESTAMP NOT NULL WITH DEFAULT,
    MEMBER_ID      CHAR(8)   NOT NULL,
    GP_CPU_SEC     DOUBLE    NOT NULL,
    ZIIP_CPU_SEC   DOUBLE    NOT NULL,
    OFFLOAD_PCT    DECIMAL(5,2) GENERATED ALWAYS AS (
        CASE WHEN (GP_CPU_SEC + ZIIP_CPU_SEC) > 0 
             THEN (ZIIP_CPU_SEC / (GP_CPU_SEC + ZIIP_CPU_SEC)) * 100
             ELSE 0.0 END
    ),
    PRIMARY KEY (RUN_TIMESTAMP, MEMBER_ID)
) IN DB2DATA.MATRPERF;
